# Form implementation generated from reading ui file 'loginform.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui
from PyQt6.QtWidgets import QApplication, QMainWindow, QWidget, QLabel
from PyQt6.QtWidgets import QFrame, QPushButton, QVBoxLayout, QHBoxLayout, QLineEdit
from PyQt6.QtGui import QPalette

from overrides import clickableLabel, set_position

class winLogin(QMainWindow):
    def __init__(self, app, position=None):
        super().__init__()
        self.ui = Ui_winLogin()
        # Fetch the app's palette in order to set colors that derive from the applied theme
        palette = app.palette()
        baseColor = palette.color(QPalette.ColorRole.Base)  # Get base color
        lighterColor = baseColor.lighter(120) # 120% lighter than base color
        
        # Define styles
        styles = {
             "lineEdit": f"background-color: {lighterColor.name()};border-radius: 5px;height: 30px;" 
        }

        self.ui.setupUi(self, styles, app)

        if position:
            set_position(self, position)
            


class Ui_winLogin(object):
    def setupUi(self, winLogin, styles, app):
        # Configure main window properties
        winLogin.setObjectName("winLogin")
        winLogin.setFixedSize(300, 350)

        self.centralwidget = QWidget(parent=winLogin)
        winLogin.setCentralWidget(self.centralwidget)

        self.btnLogin = QPushButton(parent=self.centralwidget)
        self.btnLogin.setGeometry(QtCore.QRect(39, 240, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnLogin.setFont(font)
        self.btnLogin.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnLogin.setCheckable(False)
        self.btnLogin.setObjectName("btnLogin")
        self.vframeCred = QFrame(parent=self.centralwidget)
        self.vframeCred.setGeometry(QtCore.QRect(30, 70, 241, 121))
        self.vframeCred.setFrameShape(QFrame.Shape.StyledPanel)
        self.vframeCred.setFrameShadow(QFrame.Shadow.Plain)
        self.vframeCred.setLineWidth(2)
        self.vframeCred.setMidLineWidth(0)
        self.vframeCred.setObjectName("vframeCred")
        self.verticalLayout = QVBoxLayout(self.vframeCred)
        self.verticalLayout.setContentsMargins(-1, 6, -1, -1)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblUser = QLabel(parent=self.vframeCred)
        font = QtGui.QFont()
        font.setBold(True)
        self.lblUser.setFont(font)
        self.lblUser.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblUser.setObjectName("lblUser")
        self.verticalLayout.addWidget(self.lblUser)
        self.lineUser = QLineEdit(parent=self.vframeCred)
        self.lineUser.setMinimumSize(QtCore.QSize(200, 0))
        self.lineUser.setStyleSheet(styles["lineEdit"])
        self.lineUser.setEchoMode(QLineEdit.EchoMode.Normal)
        self.lineUser.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineUser.setDragEnabled(False)
        self.lineUser.setClearButtonEnabled(False)
        self.lineUser.setObjectName("lineUser")
        self.verticalLayout.addWidget(self.lineUser)
        self.lblPass = QLabel(parent=self.vframeCred)
        font = QtGui.QFont()
        font.setBold(True)
        self.lblPass.setFont(font)
        self.lblPass.setObjectName("lblPass")
        self.verticalLayout.addWidget(self.lblPass)
        self.linePass = QLineEdit(parent=self.vframeCred)
        self.linePass.setMinimumSize(QtCore.QSize(200, 0))
        self.linePass.setEchoMode(QLineEdit.EchoMode.Password)
        self.linePass.setDragEnabled(False)
        self.linePass.setStyleSheet(styles["lineEdit"])
        self.verticalLayout.addWidget(self.linePass)
        self.lblHeader = QLabel(parent=self.centralwidget)
        self.lblHeader.setGeometry(QtCore.QRect(20, 20, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.lblHeader.setFont(font)
        self.lblHeader.setFrameShape(QFrame.Shape.NoFrame)
        self.lblHeader.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblHeader.setObjectName("lblHeader")
        self.hzwigRedirect = QWidget(parent=self.centralwidget)
        self.hzwigRedirect.setGeometry(QtCore.QRect(40, 280, 211, 31))
        self.hzwigRedirect.setObjectName("hzwigRedirect")
        self.horizontalLayout = QHBoxLayout(self.hzwigRedirect)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblAskAcc = QLabel(parent=self.hzwigRedirect)
        self.lblAskAcc.setMinimumSize(QtCore.QSize(135, 0))
        self.lblAskAcc.setMaximumSize(QtCore.QSize(135, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblAskAcc.setFont(font)
        self.lblAskAcc.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.lblAskAcc.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblAskAcc.setIndent(-1)
        self.lblAskAcc.setObjectName("lblAskAcc")
        self.horizontalLayout.addWidget(self.lblAskAcc)
        self.lblSignup = clickableLabel(parent=self.hzwigRedirect, root=winLogin, app=app, type=1)
        self.lblSignup.setEnabled(True)
        self.lblSignup.setMinimumSize(QtCore.QSize(50, 0))
        self.lblSignup.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.lblSignup.setFont(font)
        self.lblSignup.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.lblSignup.setStyleSheet("color: rgb(0, 170, 255);")
        self.lblSignup.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblSignup.setWordWrap(False)
        self.lblSignup.setObjectName("lblSignup")
        self.horizontalLayout.addWidget(self.lblSignup)
        self.lblErrors = QLabel(parent=self.centralwidget)
        # Hide by default
        self.lblErrors.setVisible(False)
        self.lblErrors.setGeometry(QtCore.QRect(40, 195, 241, 31))
        self.lblErrors.setStyleSheet("color: red;")
        self.lblErrors.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.lblErrors.setObjectName("lblErrors")

        self.retranslateUi(winLogin)

    def retranslateUi(self, winLogin):
        _translate = QtCore.QCoreApplication.translate
        winLogin.setWindowTitle(_translate("winLogin", "Login Form"))
        self.btnLogin.setText(_translate("winLogin", "Login"))
        self.lblUser.setText(_translate("winLogin", "<html><head/><body><p>Username:<span style=\" color:red;\">*</span></p></body></html>"))
        self.lineUser.setPlaceholderText(_translate("winLogin", "username or email"))
        self.lblPass.setText(_translate("winLogin", "<html><head/><body><p>Username:<span style=\" color:red;\">*</span></p></body></html>"))
        self.linePass.setPlaceholderText(_translate("winLogin", "password"))
        self.lblHeader.setText(_translate("winLogin", "Login"))
        self.lblAskAcc.setText(_translate("winLogin", "Don\'t have an account?"))
        self.lblSignup.setText(_translate("winLogin", "Sign Up"))
        self.lblErrors.setText(_translate("winLogin", "Error messages go here"))


if __name__ == "__main__":
    import sys

    app = QApplication(sys.argv)
    #app.setStyle("") # windows, windowsvista, fusion, or custom styles
    window = winLogin(app)
    window.show()

    sys.exit(app.exec())